"""
Generates a fixed bank of reference-view screenshots (+ camera metadata) for a
volume, for later image-embedding-based camera/view diagnosis.

This does NOT touch the existing agent-reasoning pipeline (session.py,
prompt_writer.py, spatial_knowledge.py, action_parser.py) — it's a standalone
addition that reuses the same low-level VTK rendering primitives from
volume_scene.py (load_raw_volume, build_isosurface_pipeline, save_screenshot).

How it works:
  1. The camera is set to a single manually-calibrated "Dorsal" configuration
     (INITIAL_DORSAL_CAMERA below — this is the ONLY place you should need to edit
     to calibrate the pipeline against your actual dataset).
  2. For each of the 18 named views in VIEW_ANGLES, the camera is reset back to
     that exact Dorsal configuration, then a relative Azimuth/Elevation rotation
     is applied. Nothing is cumulative — every view starts from the same numbers,
     so there is no drift between views regardless of order.
  3. Each view's screenshot and full camera state are saved.
"""
import json
from pathlib import Path
from typing import Dict, List, Tuple

from .volume_scene import build_isosurface_pipeline, load_raw_volume, save_screenshot

# ======================================================================
# CALIBRATION — edit ONLY this block to match your actual dataset.
#
# This is treated as the canonical "Dorsal" view: every other view below is
# generated by resetting the camera to these exact numbers, then rotating.
# Replace with your manually-calibrated camera once you have it.
# ======================================================================
INITIAL_DORSAL_CAMERA = {
    "position": (-624.664, 118.625, 121.945),      # <-- EDIT: calibrated Dorsal camera position
    "focal_point": (142.426, 118.625, 121.945),    # <-- EDIT: calibrated Dorsal focal point
    "view_up": (0.0, 1.0, 0.0),                    # <-- EDIT: calibrated Dorsal view-up vector
    "parallel_projection": False,                  # <-- EDIT: True for orthographic/parallel projection
    "parallel_scale": None,                        # <-- EDIT: only used if parallel_projection is True
}

# ======================================================================
# VIEW ANGLE TABLE — (azimuth_degrees, elevation_degrees), applied via
# vtkCamera.Azimuth()/Elevation() right after resetting to INITIAL_DORSAL_CAMERA.
#
# Edit signs here (not the calibration above) if Medial/Lateral or
# Distal/Proximal come out swapped once you inspect the generated images.
# ======================================================================
VIEW_ANGLES: Dict[str, Tuple[float, float]] = {
    # Canonical views
    "Dorsal": (0, 0),
    "Plantar": (0, 180),
    "Medial": (-90, 0),
    "Lateral": (90, 0),
    "Distal": (0, 90),
    "Proximal": (0, -90),
    # Two-axis oblique views
    "DorsalMedial": (-45, 0),
    "DorsalLateral": (45, 0),
    "DorsalDistal": (0, 45),
    "DorsalProximal": (0, -45),
    "PlantarMedial": (-45, 180),
    "PlantarLateral": (45, 180),
    "PlantarDistal": (0, 135),
    "PlantarProximal": (0, -135),
    "MedialDistal": (-90, 45),
    "MedialProximal": (-90, -45),
    "LateralDistal": (90, 45),
    "LateralProximal": (90, -45),
}


def _reset_to_initial_dorsal(camera) -> None:
    """Reset the camera to the exact calibrated Dorsal configuration. Called before
    every view so rotations never accumulate from one view to the next.
    """
    camera.SetPosition(*INITIAL_DORSAL_CAMERA["position"])
    camera.SetFocalPoint(*INITIAL_DORSAL_CAMERA["focal_point"])
    camera.SetViewUp(*INITIAL_DORSAL_CAMERA["view_up"])


def _camera_metadata(view_name: str, image_path: str, azimuth: float, elevation: float, camera) -> dict:
    parallel = bool(camera.GetParallelProjection())
    return {
        "view_name": view_name,
        "image_path": image_path,
        "azimuth": azimuth,
        "elevation": elevation,
        "position": list(camera.GetPosition()),
        "focal_point": list(camera.GetFocalPoint()),
        "view_up": list(camera.GetViewUp()),
        "direction_of_projection": list(camera.GetDirectionOfProjection()),
        "clipping_range": list(camera.GetClippingRange()),
        "parallel_projection": parallel,
        "parallel_scale": camera.GetParallelScale() if parallel else None,
    }


def generate_reference_views(
    raw_path: str,
    dimensions: tuple,
    scalar_type: str = "uint8",
    isovalue: float = 80,
    output_dir: str = "reference_views",
) -> List[dict]:
    """Render and save all 18 reference views + their metadata.

    Output layout:
      {output_dir}/{ViewName}.png            (one per view in VIEW_ANGLES)
      {output_dir}/reference_views_metadata.json

    Returns the list of per-view metadata dicts (the same content written to the
    metadata JSON).
    """
    image_data = load_raw_volume(raw_path, dimensions, scalar_type)
    _actor, renderer, render_window = build_isosurface_pipeline(image_data, isovalue)
    camera = renderer.GetActiveCamera()

    camera.SetParallelProjection(INITIAL_DORSAL_CAMERA["parallel_projection"])
    if INITIAL_DORSAL_CAMERA["parallel_projection"] and INITIAL_DORSAL_CAMERA["parallel_scale"]:
        camera.SetParallelScale(INITIAL_DORSAL_CAMERA["parallel_scale"])

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    metadata = []
    for view_name, (azimuth, elevation) in VIEW_ANGLES.items():
        _reset_to_initial_dorsal(camera)
        camera.Azimuth(azimuth)
        camera.Elevation(elevation)
        camera.OrthogonalizeViewUp()
        renderer.ResetCameraClippingRange()

        image_path = out_dir / f"{view_name}.png"
        save_screenshot(render_window, str(image_path))

        metadata.append(_camera_metadata(view_name, str(image_path), azimuth, elevation, camera))
        print(f"[reference_views] Saved {view_name} -> {image_path}")

    metadata_path = out_dir / "reference_views_metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"[reference_views] Wrote metadata for {len(metadata)} views to {metadata_path}")

    return metadata
